v2

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,5 +1,19 @@
 #!/bin/sh
 
+
+if [[ -z "$KUBE_URL" ]]; then
+  echo "Missing KUBE_URL."
+  exit 1
+fi
+if [[ -z "$KUBE_TOKEN" ]]; then
+  echo "Missing KUBE_TOKEN."
+  exit 1
+fi
+if [[ -z "$KUBE_NAMESPACE" ]]; then
+  echo "Missing KUBE_NAMESPACE."
+  exit 1
+fi
+
 # get folder with k8s objects
 FOLDER=$1
 
@@ -16,13 +30,30 @@ do
 done
 
 # authenticate kubectl
-echo "Authenticating to cluster: $K8S_MASTER_HOST"
-kubectl config set-cluster default-cluster --insecure-skip-tls-verify=true --server=$K8S_MASTER_HOST 
-kubectl config set-credentials default-admin --username=$K8S_ADMIN --password $K8S_PASSWORD
+echo "Authenticating to cluster: $KUBE_URL"
+export KUBE_CLUSTER_OPTIONS=
+if [[ -n "$KUBE_CA_PEM" ]]; then
+  echo "Using KUBE_CA_PEM..."
+  echo "$KUBE_CA_PEM" > "$(pwd)/kube.ca.pem"
+  export KUBE_CLUSTER_OPTIONS=--certificate-authority="$(pwd)/kube.ca.pem"
+fi
+kubectl config set-cluster default-cluster --insecure-skip-tls-verify=true --server=$KUBE_URL $KUBE_CLUSTER_OPTIONS
+kubectl config set-credentials default-admin --token=$KUBE_TOKEN $KUBE_CLUSTER_OPTIONS
 kubectl config set-context default-context --user=default-admin --cluster=default-cluster
 kubectl config use-context default-context
 
 # deploy objects to k8s 
+echo "Creating namespace..."
+cat <<EOF | kubectl apply -f -
+kind: Namespace
+apiVersion: v1
+metadata:
+  name: $CI_PROJECT_NAMESPACE
+EOF
+
 echo "Deploying objects..."
 kubectl apply -f /data
+
+echo "Checking deployment status..."
+kubectl rollout status deployment/$CI_PROJECT_NAME --namespace=$CI_PROJECT_NAMESPACE
 
